
<div class="container">
  <div class="row">
   
  </div>
  <!--  -->
  <div class="row about">
    <div class="col-md-offset-0 col-md-12">
      <h3 class="about-title"><?php echo $title; ?></h3>
      <p class="text-left about-desc">
        <h2>Terms of service <?php echo config_item('company_name') ?></h2><br>
        <small>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </small><br><br>

         <small>This website www.<?php echo $_SERVER['HTTP_HOST'] ?> (hereinafter referred to as "<?php echo $_SERVER['HTTP_HOST'] ?>" or "Site" or "we" or "us") is a service provided by <?php echo config_item('company_name') ?>. The products that you purchase using this Site would be sold to you by <?php echo config_item('company_name') ?>. Your use of this Site and related services and tools are governed by the following terms and conditions. If you transact on <?php echo $_SERVER['HTTP_HOST'] ?>, you shall be subject to the policies that are applicable to the Site for such transaction. By mere use of the website you shall be contracting with Hit the <?php echo config_item('company_name') ?>., a company incorporated under the laws of INDIA with its registered office at <?php echo config_item('company_address') ?>. You agree that you have read and understood these Terms of Use and that you would be bound by these Terms of Use till such time as you may access the Site. If you do not wish to be bound by these Terms of Use, please do not use this Site.
         </small> 

          <small>
            For the purpose of these Terms of Use, wherever the context so require ‘you’ shall mean any natural or legal person who has agreed to become a member of the Website by providing registration data while registering on the Site as registered user using the computer systems of <?php echo $_SERVER['HTTP_HOST'] ?>.
          </small>
          <br><br>
         <small>
          When you use any of the services provided on the Site, including but not limited to customer reviews, etc., you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. However please note that your purchase of products from the Site shall be governed by the Product Policy (as detailed below). <?php echo $_SERVER['HTTP_HOST'] ?> reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to such changes to these Terms of Use. As long as you comply with these Terms of Use and the Product Policy, <?php echo $_SERVER['HTTP_HOST'] ?> grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.
          <br><br>
          Accessing, browsing or otherwise using the Site indicates your agreement to all the terms and conditions in these Terms of Use, so please read this agreement carefully before proceeding.
         </small>

          <br><br>
          <h2>General</h2><br>
          <small>
            These Terms of Use have been executed and delivered by you and constitute a valid and binding agreement between you and <?php echo $_SERVER['HTTP_HOST'] ?>, enforceable against you in accordance with their terms. You represent that (1) you are at least 18 years of age, (2) you are not incapacitated to form a binding contract, (3) in case you are registering as a member on behalf of a corporate body, you represent that you have the requisite authority to bind such corporate body and (3) that all of the information, data and other materials you provide on this Site or to <?php echo $_SERVER['HTTP_HOST'] ?> through any other means are true, accurate, current and complete. You are responsible for updating and correcting the information you have provided on this Site, as appropriate.
          </small><br><Br>
          <small>
            You shall establish and use your membership on the Site, and purchase and use the products and services available through the Site in strict compliance with these Terms of Use and all applicable policies, laws, rules and regulations. All calls, emails and other communications between you and <?php echo $_SERVER['HTTP_HOST'] ?> may be recorded.
          </small>
          
           <br><br>
          <h2>Product policy</h2><br>
          <small>The Product Policy governs all aspects of your purchase of products through the Site.</small>

          <br><br>
          <h2><?php echo $_SERVER['HTTP_HOST'] ?> membership</h2><br>
          <ol>
            <li>Establishing a Membership</li><br>
              <small>You may establish membership on the Site. At a minimum, enrolment requires you to (1) indicate agreement to these Terms of Use and the Product Policy, (2) provide contact information and identification details, and (3) submit any other form of authentication required as part of the enrolment process, in <?php echo $_SERVER['HTTP_HOST'] ?>’s sole discretion. You agree to accept responsibility for all activities that occur under your account or password. You are responsible for maintaining the confidentiality of your account and password, and for restricting access to your account. We shall not be responsible for any unauthorized use of your account with <?php echo $_SERVER['HTTP_HOST'] ?> which may result from any failure by you to protect the confidentiality of your account details.</small>

               <li>Use of Membership</li><br>
                <small>You shall not use your <?php echo $_SERVER['HTTP_HOST'] ?> membership for any purpose competitive to <?php echo $_SERVER['HTTP_HOST'] ?>. You will notify <?php echo $_SERVER['HTTP_HOST'] ?> immediately by emailing support@<?php echo $_SERVER['HTTP_HOST'] ?> of any actual or suspected unauthorized use of your <?php echo $_SERVER['HTTP_HOST'] ?> membership or the Site known to you, whether by you or a third party.
                </small>

                <li>Membership Termination</li><br>
                <small>You may cancel your <?php echo $_SERVER['HTTP_HOST'] ?> membership at any time by contacting <?php echo $_SERVER['HTTP_HOST'] ?> customer support as specified on the “Contact Us” page on the Site. <?php echo $_SERVER['HTTP_HOST'] ?> may terminate your membership and refuse any and all current or future use of the Site or other services, or any portion thereof, (1) in order to comply with applicable laws, (2) if you provide any information that <?php echo $_SERVER['HTTP_HOST'] ?> determines, in its sole discretion, to be untrue, inaccurate, not current or incomplete (or if the information becomes untrue, inaccurate, not current or incomplete), (3) if <?php echo $_SERVER['HTTP_HOST'] ?> determines, in its sole discretion, that you are using your <?php echo $_SERVER['HTTP_HOST'] ?> membership in a manner not permitted by these Terms of Use, or (4) in other circumstances, as <?php echo $_SERVER['HTTP_HOST'] ?> deems appropriate in its sole discretion.
                </small>
          </ol>

        <br><br>
          <h2>Content you submit</h2><br>
          <strong>You acknowledge that you are responsible for any content you may submit through the Site, including the legality, reliability, appropriateness, originality and copyright of any such content. You may not upload to, host, display, modify, transmit, update, share, distribute or otherwise publish through this Site any content that: </strong>
          <ol>
            <li>is confidential, proprietary, invasive of privacy or publicity rights, infringing on patents, trademarks, copyrights, or other intellectual property rights, unlawful, harmful, threatening, false, fraudulent, libellous, defamatory, obscene, vulgar, pornographic, paedophilic, profane, abusive, harassing, hateful, racially, ethnically or otherwise objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever, including, but not limited to any content that encourages conduct that would constitute a criminal offence, violates the rights of any party or otherwise gives rise to civil liability or otherwise violates any applicable laws for the time being in force;</li>
            <li>belongs to another person and to which you do not have any right to;</li>
            <li>harms minors in any way;</li>
            <li>deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
            <li>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence of prevents investigation of any offence or is insulting to any other nation;</li>
            <li>infringes upon or violates any third party's privacy rights (including without limitation unauthorized disclosure of a person's name, physical address, phone number or email address);</li>
          </ol>
        <br><br><h2>Links</h2><br>
        This Site may contain links to other websites or resources that are operated by third parties not affiliated with <?php echo $_SERVER['HTTP_HOST'] ?>. These links are provided as a convenience to you and as an additional avenue of access to the information contained therein. We are not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. Inclusion of links to other sites or resources should not be viewed as an endorsement of the content of linked sites or resources. Different terms and conditions and privacy policies may apply to your use of any linked sites or resources. <?php echo $_SERVER['HTTP_HOST'] ?> is not responsible or liable, directly or indirectly, for any damage, loss or liability caused or alleged to be caused by or in connection with any use of or reliance on any such content, products or services available on or through any such linked site or resource.
        
        <br><br><h2>Disclaimers</h2><br>
      <small>  EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THESE TERMS OF USE, OR REQUIRED BY APPLICABLE LAW, <?php echo $_SERVER['HTTP_HOST'] ?> MAKES NO REPRESENTATIONS, COVENANTS OR WARRANTIES AND OFFERS NO OTHER CONDITIONS, EXPRESS OR IMPLIED, REGARDING ANY MATTER, INCLUDING, WITHOUT LIMITATION, THE MERCHANTABILITY, SUITABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, OR NON-INFRINGEMENT OF <?php echo $_SERVER['HTTP_HOST'] ?> MEMBERSHIP, ANY CONTENT ON THE SITE, OR ANY PRODUCTS OR SERVICES PURCHASED THROUGH THE SITE, AS WELL AS WARRANTIES IMPLIED FROM A COURSE OF PERFORMANCE OR COURSE OF DEALING.</small><br><br>
      <small>
      YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. THE SITE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. WE RESERVE THE RIGHT TO RESTRICT OR TERMINATE YOUR ACCESS TO THE SITE OR ANY FEATURE OR PART THEREOF AT ANY TIME. <?php echo $_SERVER['HTTP_HOST'] ?> DISCLAIMS ANY WARRANTIES THAT ACCESS TO THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE; THAT THE SITE WILL BE SECURE; THAT THE SITE OR THE SERVER THAT MAKES THE SITE AVAILABLE WILL BE VIRUS-FREE; OR THAT INFORMATION ON THE SITE WILL BE CORRECT, ACCURATE, ADEQUATE, USEFUL, TIMELY, RELIABLE OR OTHERWISE COMPLETE. IF YOU DOWNLOAD ANY CONTENT FROM THIS SITE, YOU DO SO AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH CONTENT. NO ADVICE OR INFORMATION OBTAINED BY YOU FROM THE SITE SHALL CREATE ANY WARRANTY OF ANY KIND.</small>
      <br><br><h2>Children's Privacy
      </h2><br>
      Our Services do not address anyone under the age of 13. We do not knowingly collect personal identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.


<br><br><h2>Limitation of liability</h2><br>
<small>YOU ACKNOLWEDGE AND AGREE THAT <?php echo $_SERVER['HTTP_HOST'] ?> MERELY PROVIDES THE SITE AND THE PROVIDERS WHOSE PRODUCTS AND SERVICES ARE AVAILABLE ON THE <?php echo $_SERVER['HTTP_HOST'] ?> SITES ARE INDEPENDENT CONTRACTORS AND NOT AGENTS OR EMPLOYEES OF <?php echo $_SERVER['HTTP_HOST'] ?>. <?php echo $_SERVER['HTTP_HOST'] ?> IS NOT LIABLE FOR THE ACTS, ERRORS, OMISSIONS, REPRESENTATIONS, WARRANTIES, BREACHES OR NEGLIGENCE OF ANY SUCH THIRD PARTIES OR FOR ANY PERSONAL INJURIES, DEATH, PROPERTY DAMAGE, OR OTHER DAMAGES OR EXPENSES RESULTING THEREFROM.
</small><br><br>
<small>
  YOU ACKNOWLEDGE AND AGREE THAT YOU ASSUME FULL RESPONSIBILITY FOR YOUR USE OF THE SITE AND/OR FOR USE OF SITE'S MEMBERSHIP, COMMUNICATIONS WITH THIRD PARTIES, AND PURCHASE AND USE OF THE PRODUCTS AND SERVICES AVAILABLE THROUGH THE SITE. WITH RESPECT TO THIRD PARTY USER GENERATED CONTENT, <?php echo $_SERVER['HTTP_HOST'] ?> NEITHER ORIGINATES NOR INITIATES ANY TRANSMISSION ON THE SITE NOR SELECTS THE SENDER AND RECEIVER OF A TRANSMISSION NOR SELECTS NOR MODIFIES THE INFORMATION CONTAINED IN A TRANSMISSION. <?php echo $_SERVER['HTTP_HOST'] ?> HAS NO CONTROL OVER THE THIRD PARTY USER GENERATED CONTENT IN THE SITE AND ACTS AS AN "INTERMEDIARY" AS UNDERSTOOD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 WITH RESPECT TO ALL THIRD PARTY USER GENERATED CONTENT.
</small><br><br>
<small>
  YOU ACKNOWLEDGE AND AGREE THAT ANY INFORMATION YOU SEND OR RECEIVE DURING YOUR MEMBERSHIP AND/OR USE OF THE SITE MAY NOT BE SECURE AND MAY BE INTERCEPTED BY UNAUTHORIZED PARTIES. YOU ACKNOWLEDGE AND AGREE THAT YOUR USE OF THE SITE IS AT YOUR OWN RISK AND THAT THE SITE IS MADE AVAILABLE TO YOU AT NO CHARGE. RECOGNIZING SUCH, YOU ACKNOWLEDGE AND AGREE THAT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, NEITHER <?php echo $_SERVER['HTTP_HOST'] ?> NOR ITS LICENSORS, SUPPLIERS OR THIRD PARTY CONTENT PROVIDERS WILL BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, EXEMPLARY, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR OTHER DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO (1) THIS SITE, OR ANY OTHER SITE OR RESOURCE YOU ACCESS THROUGH A LINK FROM THIS SITE; (2) ANY ACTION WE TAKE OR FAIL TO TAKE AS A RESULT OF COMMUNICATIONS YOU SEND TO US; (3) YOUR <?php echo $_SERVER['HTTP_HOST'] ?> MEMBERSHIP, ANY TERMINATION OR CANCELATION OF YOUR MEMBERSHIP, ANY REFERRAL CREDIT PROGRAM (OR ASSOCIATED CREDITS); (4) ANY PRODUCTS OR SERVICES MADE AVAILABLE OR PURCHASED THROUGH THE SITE; (5) ANY FRAUDULENT ACT COMMITTED BY ANY PERSON USING THE SITE WHICH MAY OR MAY NOT INVOLVE FINANCIAL TRANSACTIONS, INCLUDING ANY DAMAGES OR INJURY ARISING FROM ANY USE OF SUCH PRODUCTS OR SERVICES; (5) ANY DELAY OR INABILITY TO USE THE SITE OR ANY INFORMATION, PRODUCTS OR SERVICES ADVERTISED IN OR OBTAINED THROUGH THE SITE;<br><br> (6) THE MODIFICATION, REMOVAL OR DELETION OF ANY CONTENT SUBMITTED OR POSTED ON THE SITE; OR (7) ANY USE OF THE SITE, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY OR OTHERWISE, EVEN IF <?php echo $_SERVER['HTTP_HOST'] ?> HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY OPINION, ADVICE OR OTHER CONTENT AVAILABLE THROUGH THE SITE, OR OBTAINED FROM A LINKED SITE OR RESOURCE. THIS DISCLAIMER APPLIES, WITHOUT LIMITATION, TO ANY DAMAGES OR INJURY ARISING FROM ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, FILE CORRUPTION, COMMUNICATION-LINE FAILURE, NETWORK OR SYSTEM OUTAGE, LOSS OF PROFITS BY YOU, OR THEFT, DESTRUCTION, UNAUTHORIZED ACCESS TO, ALTERATION OF, LOSS OR USE OF ANY RECORD OR DATA, AND ANY OTHER TANGIBLE OR INTANGIBLE LOSS. YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT NEITHER <?php echo $_SERVER['HTTP_HOST'] ?> NOR ITS LICENSORS, SUPPLIERS, FRANCHISEES OR THIRD PARTY CONTENT PROVIDERS SHALL BE LIABLE FOR ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY USER OF THE SITE. YOUR REMEDY FOR ANY OF THE ABOVE CLAIMS OR ANY DISPUTE WITH <?php echo $_SERVER['HTTP_HOST'] ?> IS TO DISCONTINUE YOUR USE OF THE SITE. YOU AND <?php echo $_SERVER['HTTP_HOST'] ?> AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES OR THE CAUSE OF ACTION IS PERMANENTLY BARRED.NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED ELSEWHERE, <?php echo $_SERVER['HTTP_HOST'] ?>'S TOTAL LIABILITY TOWARDS YOU FOR ALL LIABILITIES ARISING FROM YOUR USE OF THE SITE OR PURCHASING PRODUCTS USING THE SITE SHALL NOT, BE IT IN TORT OR CONTRACT, EXCEED THE AMOUNT PAID BY YOU TO <?php echo $_SERVER['HTTP_HOST'] ?>'S FRANCHISEES AGAINST THE VALUE OF THE PRODUCTS ORDERED BY YOU USING THE SITE.
</small><br><br>

<br><br><h2>Grievance officer
</h2><br>If you have any questions or comments about these Terms of Use, please contact us by email at support@<?php echo $_SERVER['HTTP_HOST'] ?> If you notice any discrepancies in the information provided to us or have any grievance against us, you may contact our Grievance Officer. The details of the Grievance Officer are as follows: grievance@<?php echo $_SERVER['HTTP_HOST'] ?>
</p>
    </div>
    <div class="skill">
    
    </div>
   
  </div>

</div>
